# Generated by Django 5.2.6 on 2025-09-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contract_pdf_file_contract_pdf_generated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='offers/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_pdf_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('sent', 'Sent')], default='draft', max_length=16),
        ),
    ]
