# Generated by Django 5.0.14 on 2025-09-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_company_email_offer_offer_pdf_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='auto_renew',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='renewal_period_months',
            field=models.PositiveSmallIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='contract',
            name='service_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('canceled', 'Canceled')], default='active', max_length=16),
        ),
    ]
