# Generated by Django 5.0.14 on 2025-09-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_contract_auto_renew_contract_renewal_period_months_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='last_renewal_proposal_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
